# Generated by Django 6.0.1 on 2026-01-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.IntegerField(blank=True, max_length=5, null=True, unique=True)),
            ],
            options={
                'db_table': 'obrasocial',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.IntegerField(max_length=20, unique=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('obrasocial_id', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
