# Generated by Django 6.0.1 on 2026-01-20 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HsitoriaEstadoTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('EN_TRASLADO', 'En traslado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('EN_TRASLADO', 'En traslado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SIMPLE', 'Simple'), ('ARM', 'ARM '), ('CODIGO_ROJO', 'Código Rojo')], default='SIMPLE', max_length=20)),
                ('sub_tipo', models.CharField(choices=[('ESTUDIO', 'Estudio'), ('DERIVACION', 'Derivacion'), ('INTERCONSULTA', 'Interconsulta'), ('DOMICILIO', 'Domicilio')], default='ESTUDIO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('EN_TRASLADO', 'En traslado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('requiere_medico', models.BooleanField(default=False)),
                ('ambulancia_privada', models.BooleanField(default=False)),
                ('turno_fecha', models.DateField(blank=True, null=True)),
                ('turno_hora', models.TimeField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
