# Generated by Django 6.0.1 on 2026-01-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('traslado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hsitoriaestadotraslado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traslado',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_chofer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traslado',
            name='enfermeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_enfermeria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traslado',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='traslado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsitoriaestadotraslado',
            name='traslado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='traslado.traslado'),
        ),
    ]
